import{a as L,i,S as g}from"./assets/vendor-09d7c26e.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))e(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const p of o.addedNodes)p.tagName==="LINK"&&p.rel==="modulepreload"&&e(p)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function e(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();const v="43937771-7a09e506748022e7cd8e25746",w="https://pixabay.com/api/";async function m(s,r=1,n=15){try{return(await L.get(w,{params:{key:v,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:n}})).data}catch(e){throw console.error(e),e}}function y(s,r){if(s.length===0){iziToast.error({title:"Error",position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"});return}const n=s.map(e=>`
    <div class="image-card">
      <a href="${e.largeImageURL}"><img src="${e.webformatURL}" alt="${e.tags}" title=""/></a>
      <div class="image-info">
        <p><span>Перегляди: </span>${e.views}</p>
        <p><span>Загрузки: </span>${e.downloads}</p>
        <p><span>Лайки: </span>${e.likes}</p>
        <p><span>Коменти: </span>${e.comments}</p>
      </div>
    </div>
  `).join("");r.insertAdjacentHTML("beforeend",n)}let l=1,c="";const h=15,a=document.querySelector("#loader"),f=document.querySelector("#search-input"),d=document.querySelector("#gallery"),b=document.querySelector("#search-form"),u=document.querySelector("#load-more-btn");b.addEventListener("submit",async s=>{if(s.preventDefault(),d.innerHTML="",c=f.value.trim(),l=1,u.classList.add("hidden"),!c){i.warning({title:"Warning",position:"topRight",message:"Please enter a search query."});return}a.classList.remove("hidden");try{const{hits:r,totalHits:n}=await m(c,l,h);if(a.classList.add("hidden"),r.length===0){i.error({title:"Error",position:"topRight",message:"No images found. Please try a different query."});return}y(r,d),new g(".image-card a",{captionsData:"alt",captionDelay:250}),r.length>=h&&u.classList.remove("hidden"),f.value=""}catch{a.classList.add("hidden"),i.error({title:"Error",position:"topRight",message:"Something went wrong. Please try again."})}});u.addEventListener("click",async()=>{l+=1,a.classList.remove("hidden");try{const{hits:s,totalHits:r}=await m(c,l,h);a.classList.add("hidden"),y(s,d),new g(".image-card a",{captionsData:"alt",captionDelay:250}).refresh();const{height:e}=document.querySelector(".image-card").getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"}),d.children.length>=r&&(u.classList.add("hidden"),i.info({title:"Info",position:"topRight",message:"We're sorry, but you've reached the end of search results."}))}catch{}});
//# sourceMappingURL=commonHelpers.js.map
